### ISSUE TITLE
Generating error instead of the leetcode status card

### ISSUE THREAD

**Issue by AlexGabi17** [JacobLinCool/LeetCode-Stats-Card#115] opened 2024-03-06 14:26 UTC
![image](https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/39965333/08ce37d8-1dd4-46fd-bc57-b17f1593e2fe)

**Comment by MatveyGuralskiy** [comment] 2024-03-06 16:12
Also have this message, and the stats card not displayed on profile

**Comment by JacobLinCool** [comment] 2024-03-06 16:46
Confirmed, I'll work on a fix today.

**Comment by JacobLinCool** [comment] 2024-03-07 04:39
It works normally in the local development environment.

I observed a relatively higher request rate over the past 24 hours.

<img width="582" alt="截圖 2024-03-07 中午12 10 31" src="https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/28478594/fae199bf-6525-4985-9d92-6556f35b4b6d">

It seems that the workers triggered Cloudflare's bot protection on the LeetCode API but I'm not sure if the high request rate is the cause. Currently, I have no idea how to bypass the bot protection, but I'll keep monitoring the situation.

For any emergency usage, please try to duplicate the worker (`pnpm build && pnpm deploy`) or self host it with `docker compose up`.

**Comment by ValseLee** [comment] 2024-03-07 10:25
Is this related issue?

![capt](https://github.com/JacobLinCool/LeetCode-Stats-Card/assets/82270058/9db0eafe-3334-4ba7-9687-f876b72dcbc8)

**Comment by JacobLinCool** [comment] 2024-03-07 14:28
> Is this related issue?

Yes, that's the same problem. A 403 status is returned from the upstream LeetCode API.

It seems that LeetCode has now applied a captcha to all requests from Cloudflare Workers.

**Comment by ValseLee** [comment] 2024-03-07 14:32
> Owner

oh.. that sounds bad.. hope it will be resolved in better way soon

**Comment by JacobLinCool** [comment] 2024-03-12 09:23
It seems that LeetCode has removed their bot protection. I've transferred the service back to Cloudflare Workers.

**Closed by JacobLinCool** 2024-03-12 09:23 UTC
